apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260518-234615-el7r6a9yyme0-service
spec:
  selector:
    app: enterprise-system-20260518-234615-el7r6a9yyme0
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
